language: node_js
node_js:
  - '0.10'
before_install:
  - 'npm install -g istanbul'
  - 'npm install -g karma'
  - 'npm install -g karma-cli'
  - 'npm install -g grunt'
  - 'npm install -g grunt-cli'
before_script:
  - 'npm install -g grunt-cli'
  - 'npm install -g bower'
  - 'bower install -f'
